"""Centralized reason codes for optimization reject/prune events."""

from enum import Enum


class ReasonCode(str, Enum):
    MISSING_STRESSED_FOLD = "MISSING_STRESSED_FOLD"
    EARLY_TRADE_STARVATION = "EARLY_TRADE_STARVATION"
    TOO_FEW_FOLDS = "TOO_FEW_FOLDS"
    TOO_FEW_INTERNAL_OOS_TRADES = "TOO_FEW_INTERNAL_OOS_TRADES"
    TOO_FEW_TRADES = "TOO_FEW_TRADES"
    LOW_MIN_FOLD_SHARPE = "LOW_MIN_FOLD_SHARPE"
    LOW_FOLD_WIN_RATE = "LOW_FOLD_WIN_RATE"
    GUARD_TOTAL_TRADES = "GUARD_TOTAL_TRADES"
    GUARD_AVG_FOLD_TRADES = "GUARD_AVG_FOLD_TRADES"
    GUARD_EXPECTANCY = "GUARD_EXPECTANCY"
    RAW_EXPECTANCY_NONPOSITIVE = "RAW_EXPECTANCY_NONPOSITIVE"
    NEG_STRESSED_SR = "NEG_STRESSED_SR"
    NONPOSITIVE_STRESSED_EXPECTANCY = "NONPOSITIVE_STRESSED_EXPECTANCY"
    LOW_PSR = "LOW_PSR"
    PRUNED = "PRUNED"


ALL_REASON_CODES = tuple(code.value for code in ReasonCode)
